### PR TITLE
[BUG] Increasing ComicBook file name to the maximum of 260 charachters

### PR DESCRIPTION
**Pull request by apoclyps**
### What's Changed

[Linux](https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs) has a maximum filename length of 255 characters for most filesystems (including EXT4), and a maximum path of 4096 characters. In [WIndows](https://mspoweruser.com/ntfs-260-character-windows-10/) this is 260 characters. ~This PR increases the filename from `100` characters to `260` characters to avoid exceptions when importing files with large filenames.~

This PR changes the `file_name` field from a CharField to a TextField to support larger filenames containing path information.

### Technical Description

To applying the migration, run the following command:

```bash
docker-compose build app && docker-compose run app python manage.py migrate
```

Resolves the following stack trace:

```python
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/src/comic/management/commands/scan_comics.py", line 17, in handle
    self.scan_directory()
  File "/src/comic/management/commands/scan_comics.py", line 44, in scan_directory
    self.scan_directory(next_directory)
  File "/src/comic/management/commands/scan_comics.py", line 60, in scan_directory
    ComicBook.process_comic_book(file, directory)
  File "/src/comic/models.py", line 270, in process_comic_book
    book.save()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(100)
```

### CODE REVIEW

**Comment by ajurna** [comment]
I've run into this myself but i wonder would making it a textfield be a better idea?

**Comment by apoclyps** [comment]
I think a `CharField` still makes sense here as it's of fixed-length. Within Postgres there is no [performance difference among these types](https://www.postgresql.org/docs/11/datatype-character.html).

**Comment by ajurna** [comment]
the point is that with this field i think there should be no max_length. 
This field is (should at least) never be queried on.
This field holds the full file path that is in the CB* file. this is never used in a form as is only updated by the scan_comics management script.
future proofing this so that it will never need to be modified and so it can then deal with arbitrarily long file names in archives makes me feel that TextField is a better option.

**Comment by apoclyps** [comment]
thanks for the feedback and context @ajurna. I've refactored this PR to make use of a `TextField` for the `file_name`.

**Pull request merged**
