### PR TITLE
[ISSUE-4] Applying black formatting

### PR DESCRIPTION
**Pull request by apoclyps**
### What's Changed

Applies [Black](https://pypi.org/project/black/) formatting to the codebase.

Linked to #4

### CODE REVIEW

**Comment by ajurna** [comment]
i think this needs a rebase after pr #7

**Comment by apoclyps** [comment]
rebased on 7 - hit a few merge conflicts but I've just noticed some discrepancies between running the test suite using `pytest` and `python manage.py test`. 

Output of `pytest`:
image

The output of `test` command:
image

**Comment by apoclyps** [comment]
I found the issue; during the rebase, the original `tests.py` file for comics was readded and wasn't removed. This had an older version of the code that caused tests the tests to fail.

**Comment by ajurna** [comment]
looks good. thanks!

**Pull request merged**
